### ISSUE TITLE
If scheduled stream is "abandoned" it stays on the homepage but should be archived or removed. 

### ISSUE THREAD

**Issue by spaantje** [christophrumpel/larastreamers#79]
@christophrumpel You had a stream scheduled for yesterday, but never went live. So i stayed on the homepage. This could possibly happen to anyone. So i think this might be something to think about. 

We could check this in the `CheckIfUpcomingStreamsAreLiveCommand`; maybe limit this to 3 hours in the past to limit the amount of request to youtube every 5 minutes? (I don't know if you worry about the api requests?) 

Maybe we should also archive the streams after some time? (3 hours or a day or something)

What do you think?

**Comment by christophrumpel** [comment]
I think we currently have two issues:

1. the stream you saw was a test stream I did, I think it was private but I'm not sure anymore. It was automatically added because of my channel which gets checked through the commands
2. Streams that are on Larastreamers, but get deleted before they go live like `Pest in Practice | Episode 5` today.


For `2` we should use the `UpdateUpcomingStreamsCommand` command which checks all the streams hourly. If we don't get a response back from the YoutubeAPI, we should update the stream or maybe delete the stream entirely since there is no video.


For `1` I'm still not sure what exactly went wrong.

**Comment by spaantje** [comment]
We could also update the `UpdateLiveAndFinishedStreamsCommand` command to update the 50 last approved streams (so not only live & finished). That command already marks anything as deleted if we don't get any response back from youtube. 

If we do it this way, if any stream returns for whatever reason if wil show again once we get a response back. 
The command runs daily so it will be just a cleanup command. But could possibly mean that a "rogue" stream stays there for a day.

**Comment by christophrumpel** [comment]
Just ran in on the live site to make sure it deletes the broken stream, that worked 👍 Let#s see if this also solves the private stream issue. Need to try that too.

**Comment by spaantje** [comment]
I think it should, because we don't get any data back on private streams.
